---
- name: Install dependencies
  yum:
    name: libssh2-devel
    state: present

- name: Verify ssh2 extension is installed
  stat:
    path: "{{ php_extension_dir }}/ssh2.so"
  register: php_ssh2_installed_stat

- name: Check php ssh2 package is already exists
  stat:
    path: "{{ role_path }}/files/{{ php_ssh2_download_url | basename }}"
  become: false
  run_once: true
  delegate_to: localhost
  register: _php_ssh2_package_stat

- name: Download php ssh2 package
  get_url:
    url: "{{ php_ssh2_download_url }}"
    dest: "{{ role_path }}/files/"
  become: false
  run_once: true
  delegate_to: localhost
  register: _php_ssh2_package
  when:
    - not _php_ssh2_package_stat.stat.exists
    - not php_ssh2_installed_stat.stat.exists

- name: Unarchive php-ssh2 {{ php_ssh2_version }}
  unarchive:
    src: "files/{{ php_ssh2_download_url | basename }}"
    dest: /usr/local/src/
    remote_src: false
    creates: /usr/local/src/ssh2-{{ php_ssh2_version }}
  when:
    - not php_ssh2_installed_stat.stat.exists and (_php_ssh2_package is not skipped or _php_ssh2_package_stat.stat.exists)

- name: Install
  command: "{{ item }}"
  args:
    chdir: "/usr/local/src/ssh2-{{ php_ssh2_version }}"
  loop:
    - /usr/local/php/bin/phpize
    - ./configure --with-ssh2 --with-php-config=/usr/local/php/bin/php-config
    - make
    - make install
    - chown {{ php_web_user }}:{{ php_web_user }} {{ php_extension_dir }}/ssh2.so
  when:
    - not php_ssh2_installed_stat.stat.exists
  tags:
    - skip_ansible_lint

- name: Generate configuration file
  copy:
    content: "extension=ssh2.so"
    dest: /usr/local/php/etc/php.d/ssh2.ini
    mode: "644"
    owner: "{{ php_web_user }}"
    group: "{{ php_web_user }}"
  notify:
    - restart php-fpm

- name: Clean package
  file:
    path: /usr/local/src/ssh2-{{ php_ssh2_version }}
    state: absent
